import React from 'react';

const Home = () => (
  <section className="w-full pt-20 relative h-screen bg-gradient-to-r from-gray-800 to-gray-900 text-white">
    <h1 className="text-4xl mt-28 mx-10 text-red-400">Welcome to Our Page!</h1>
    {/* <img
      src={landing}
      alt="home-minimalist-bg"
      className="w-full h-screen top-0 object-cover absolute mix-blend-overlay"
    /> */}
    <p className="text-base my-8 mx-10">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque rerum atque
      optio quaerat consequuntur a facere quasi modi neque maiores veniam et
      accusamus, porro ducimus exercitationem dignissimos tempora dolore unde
      perspiciatis non pariatur quia consectetur, velit laudantium. Ut, placeat
      vero! Aut, natus omnis. Amet, magni? Soluta enim nulla necessitatibus
      quisquam nam quis, consequatur velit laudantium libero ad alias fuga
      deserunt amet provident quae ea beatae.
    </p>
    <p className="text-base my-5 mx-10">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque rerum atque
      optio quaerat consequuntur a facere quasi modi neque maiores veniam et
      accusamus, porro ducimus exercitationem dignissimos tempora dolore unde
      perspiciatis non pariatur quia consectetur, velit laudantium. Ut, placeat
      vero! Aut, natus omnis. Amet, magni? Soluta enim nulla necessitatibus
      quisquam nam quis, consequatur velit laudantium libero ad alias fuga
      deserunt amet provident quae ea beatae.
    </p>
  </section>
);

export default Home;